"use client";

import React, { useState } from "react";
import { motion } from "framer-motion";
import {
  FileText,
  Download,
  Copy,
  Mail,
  Calendar,
  DollarSign,
  Clock,
  CheckCircle,
  User,
  Building,
  Phone,
  Globe,
} from "lucide-react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

const AutomatedProposal = () => {
  const [clientDetails, setClientDetails] = useState({
    companyName: "",
    clientName: "",
    email: "",
    phone: "",
    website: "",
    projectTitle: "",
    projectDescription: "",
  });

  const [projectScope, setProjectScope] = useState({
    features: [] as string[],
    timeline: "6-8 weeks",
    budget: "$5,000 - $8,000",
    deliverables: [
      "Complete source code",
      "Documentation",
      "Deployment support",
      "30 days free maintenance",
    ],
  });

  const featureOptions = [
    "Responsive Design",
    "User Authentication",
    "Admin Dashboard",
    "Payment Integration",
    "API Development",
    "Database Design",
    "Mobile Optimization",
    "SEO Optimization",
    "Analytics Integration",
    "Email System",
  ];

  const generatePDF = async () => {
    const doc = new jsPDF();

    // Add professional header
    doc.setFillColor(41, 98, 255);
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text("SOFTXIC", 105, 20, { align: "center" });
    doc.setFontSize(12);
    doc.text("Professional Software Development Proposal", 105, 30, {
      align: "center",
    });

    // Reset color for content
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);

    // Client Details
    doc.setFontSize(16);
    doc.text("Client Information", 20, 50);
    doc.setFontSize(11);
    doc.text(
      `Company: ${clientDetails.companyName || "[Company Name]"}`,
      20,
      60
    );
    doc.text(`Client: ${clientDetails.clientName || "[Client Name]"}`, 20, 67);
    doc.text(`Email: ${clientDetails.email || "[Email]"}`, 20, 74);
    doc.text(`Phone: ${clientDetails.phone || "[Phone]"}`, 20, 81);

    // Project Details
    doc.setFontSize(16);
    doc.text("Project Overview", 20, 95);
    doc.setFontSize(11);
    doc.text(
      `Title: ${clientDetails.projectTitle || "[Project Title]"}`,
      20,
      105
    );

    const description = doc.splitTextToSize(
      clientDetails.projectDescription ||
        "[Project description will appear here]",
      170
    );
    doc.text(description, 20, 115);

    // Scope & Features
    doc.setFontSize(16);
    doc.text("Project Scope", 20, 140);
    doc.setFontSize(11);
    doc.text("Features Included:", 20, 150);

    projectScope.features.forEach((feature, index) => {
      doc.text(`• ${feature}`, 25, 157 + index * 7);
    });

    if (projectScope.features.length === 0) {
      doc.text("• [Selected features will appear here]", 25, 157);
    }

    // Timeline & Budget
    doc.setFontSize(16);
    doc.text("Project Summary", 20, 180);
    doc.setFontSize(11);
    doc.text(`Timeline: ${projectScope.timeline}`, 20, 190);
    doc.text(`Budget: ${projectScope.budget}`, 20, 197);

    // Deliverables
    doc.text("Deliverables:", 20, 207);
    projectScope.deliverables.forEach((item, index) => {
      doc.text(`• ${item}`, 25, 214 + index * 7);
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text("Generated by Hassan @ SOFTXIC", 105, 280, { align: "center" });
    doc.text(new Date().toLocaleDateString(), 105, 285, { align: "center" });

    // Save PDF
    doc.save(
      `proposal-${clientDetails.companyName || "client"}-${Date.now()}.pdf`
    );
  };

  const copyToClipboard = () => {
    const proposalText = `
PROPOSAL FOR: ${clientDetails.companyName}
CLIENT: ${clientDetails.clientName}
PROJECT: ${clientDetails.projectTitle}

OVERVIEW:
${clientDetails.projectDescription}

SCOPE:
${projectScope.features.map((f) => `• ${f}`).join("\n")}

TIMELINE: ${projectScope.timeline}
BUDGET: ${projectScope.budget}

DELIVERABLES:
${projectScope.deliverables.map((d) => `• ${d}`).join("\n")}

CONTACT:
Email: ${clientDetails.email}
Phone: ${clientDetails.phone}
    `.trim();

    navigator.clipboard.writeText(proposalText);
    alert("Proposal copied to clipboard!");
  };

  return (
    <section id="proposal-generator" className="py-20">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <div className="inline-flex items-center px-4 py-2 rounded-full bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20 mb-4">
              <FileText className="h-5 w-5 text-green-600" />
              <span className="font-medium ml-2">Free Proposal Generator</span>
            </div>
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Instant{" "}
              <span className="text-gradient">Professional Proposal</span>
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-400 max-w-3xl mx-auto">
              Generate custom project proposals in seconds - no signup required
            </p>
          </motion.div>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Left Column - Form */}
          <div className="space-y-8">
            {/* Client Details */}
            <div className="p-6 rounded-2xl bg-gradient-to-br from-blue-50 to-cyan-50 dark:from-blue-900/20 dark:to-cyan-900/20">
              <h3 className="text-xl font-bold mb-6 flex items-center">
                <User className="h-5 w-5 mr-2" />
                Client Details
              </h3>
              <div className="grid sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium mb-2">
                    Company Name
                  </label>
                  <input
                    type="text"
                    value={clientDetails.companyName}
                    onChange={(e) =>
                      setClientDetails({
                        ...clientDetails,
                        companyName: e.target.value,
                      })
                    }
                    className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-transparent"
                    placeholder="Acme Inc."
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-2">
                    Client Name
                  </label>
                  <input
                    type="text"
                    value={clientDetails.clientName}
                    onChange={(e) =>
                      setClientDetails({
                        ...clientDetails,
                        clientName: e.target.value,
                      })
                    }
                    className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-transparent"
                    placeholder="John Doe"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-2">
                    Email
                  </label>
                  <input
                    type="email"
                    value={clientDetails.email}
                    onChange={(e) =>
                      setClientDetails({
                        ...clientDetails,
                        email: e.target.value,
                      })
                    }
                    className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-transparent"
                    placeholder="john@company.com"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-2">
                    Phone
                  </label>
                  <input
                    type="tel"
                    value={clientDetails.phone}
                    onChange={(e) =>
                      setClientDetails({
                        ...clientDetails,
                        phone: e.target.value,
                      })
                    }
                    className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-transparent"
                    placeholder="+1 (234) 567-8900"
                  />
                </div>
              </div>
            </div>

            {/* Project Details */}
            <div className="p-6 rounded-2xl bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20">
              <h3 className="text-xl font-bold mb-6 flex items-center">
                <Building className="h-5 w-5 mr-2" />
                Project Details
              </h3>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-2">
                    Project Title
                  </label>
                  <input
                    type="text"
                    value={clientDetails.projectTitle}
                    onChange={(e) =>
                      setClientDetails({
                        ...clientDetails,
                        projectTitle: e.target.value,
                      })
                    }
                    className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-transparent"
                    placeholder="E-commerce Platform Development"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-2">
                    Project Description
                  </label>
                  <textarea
                    value={clientDetails.projectDescription}
                    onChange={(e) =>
                      setClientDetails({
                        ...clientDetails,
                        projectDescription: e.target.value,
                      })
                    }
                    rows={4}
                    className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-transparent resize-none"
                    placeholder="Describe your project goals, requirements, and expectations..."
                  />
                </div>
              </div>
            </div>

            {/* Features Selection */}
            <div className="p-6 rounded-2xl bg-gradient-to-br from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20">
              <h3 className="text-xl font-bold mb-6 flex items-center">
                <CheckCircle className="h-5 w-5 mr-2" />
                Select Features
              </h3>
              <div className="grid sm:grid-cols-2 gap-3">
                {featureOptions.map((feature) => (
                  <button
                    key={feature}
                    onClick={() => {
                      if (projectScope.features.includes(feature)) {
                        setProjectScope({
                          ...projectScope,
                          features: projectScope.features.filter(
                            (f) => f !== feature
                          ),
                        });
                      } else {
                        setProjectScope({
                          ...projectScope,
                          features: [...projectScope.features, feature],
                        });
                      }
                    }}
                    className={`p-3 rounded-lg border text-left transition-all ${
                      projectScope.features.includes(feature)
                        ? "border-green-500 bg-green-50 dark:bg-green-900/20"
                        : "border-gray-300 dark:border-gray-700 hover:border-gray-400 dark:hover:border-gray-600"
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-sm">{feature}</span>
                      {projectScope.features.includes(feature) && (
                        <CheckCircle className="h-4 w-4 text-green-500" />
                      )}
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Right Column - Preview & Actions */}
          <div className="space-y-8">
            {/* Proposal Preview */}
            <div className="p-6 rounded-2xl bg-white dark:bg-gray-900 border-2 border-gray-200 dark:border-gray-800 shadow-lg">
              <h3 className="text-xl font-bold mb-6 flex items-center">
                <FileText className="h-5 w-5 mr-2" />
                Proposal Preview
              </h3>

              <div className="space-y-6">
                {/* Preview Card */}
                <div className="p-4 rounded-xl bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-800 dark:to-gray-900">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <div className="font-bold text-lg">SOFTXIC</div>
                      <div className="text-sm text-gray-600 dark:text-gray-400">
                        Professional Software Development Proposal
                      </div>
                    </div>
                    <div className="text-right">
                      <div className="text-sm text-gray-600 dark:text-gray-400">
                        Date:
                      </div>
                      <div className="font-medium">
                        {new Date().toLocaleDateString()}
                      </div>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div>
                      <div className="text-sm text-gray-600 dark:text-gray-400">
                        For:
                      </div>
                      <div className="font-medium">
                        {clientDetails.companyName || "[Company Name]"}
                      </div>
                    </div>

                    <div>
                      <div className="text-sm text-gray-600 dark:text-gray-400">
                        Project:
                      </div>
                      <div className="font-medium">
                        {clientDetails.projectTitle || "[Project Title]"}
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <div className="flex items-center text-sm text-gray-600 dark:text-gray-400 mb-1">
                          <Clock className="h-4 w-4 mr-1" />
                          Timeline
                        </div>
                        <div className="font-medium">
                          {projectScope.timeline}
                        </div>
                      </div>
                      <div>
                        <div className="flex items-center text-sm text-gray-600 dark:text-gray-400 mb-1">
                          <DollarSign className="h-4 w-4 mr-1" />
                          Budget
                        </div>
                        <div className="font-medium">{projectScope.budget}</div>
                      </div>
                    </div>

                    <div>
                      <div className="text-sm text-gray-600 dark:text-gray-400 mb-2">
                        Features:
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {projectScope.features.slice(0, 3).map((feature) => (
                          <span
                            key={feature}
                            className="px-2 py-1 text-xs rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-800 dark:text-blue-300"
                          >
                            {feature}
                          </span>
                        ))}
                        {projectScope.features.length > 3 && (
                          <span className="px-2 py-1 text-xs rounded-full bg-gray-200 dark:bg-gray-800 text-gray-700 dark:text-gray-300">
                            +{projectScope.features.length - 3} more
                          </span>
                        )}
                        {projectScope.features.length === 0 && (
                          <span className="text-sm text-gray-500">
                            No features selected
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="grid sm:grid-cols-3 gap-4">
                  <button
                    onClick={generatePDF}
                    className="p-4 rounded-xl bg-gradient-to-br from-blue-600 to-cyan-500 text-white hover:from-blue-700 hover:to-cyan-600 transition-all flex flex-col items-center justify-center"
                  >
                    <Download className="h-6 w-6 mb-2" />
                    <span className="font-semibold">Download PDF</span>
                  </button>

                  <button
                    onClick={copyToClipboard}
                    className="p-4 rounded-xl bg-gradient-to-br from-purple-600 to-pink-500 text-white hover:from-purple-700 hover:to-pink-600 transition-all flex flex-col items-center justify-center"
                  >
                    <Copy className="h-6 w-6 mb-2" />
                    <span className="font-semibold">Copy Text</span>
                  </button>

                  <a
                    href={`mailto:${
                      clientDetails.email || "hassan@softxic.com"
                    }?subject=Proposal for ${
                      clientDetails.projectTitle || "Your Project"
                    }&body=Hi, here's the proposal we discussed.`}
                    className="p-4 rounded-xl bg-gradient-to-br from-green-600 to-emerald-500 text-white hover:from-green-700 hover:to-emerald-600 transition-all flex flex-col items-center justify-center"
                  >
                    <Mail className="h-6 w-6 mb-2" />
                    <span className="font-semibold">Email</span>
                  </a>
                </div>

                {/* Quick Stats */}
                <div className="grid grid-cols-3 gap-4 pt-6 border-t border-gray-200 dark:border-gray-800">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-blue-600">
                      {projectScope.features.length}
                    </div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      Features
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-green-600">
                      {projectScope.timeline.split("-")[0]}
                    </div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      Weeks
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-purple-600">
                      {projectScope.budget.split("-")[0].trim()}
                    </div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      Starting
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Benefits */}
            <div className="p-6 rounded-2xl bg-gradient-to-br from-orange-50 to-amber-50 dark:from-orange-900/20 dark:to-amber-900/20">
              <h4 className="font-bold text-lg mb-4">Why This Is Valuable:</h4>
              <ul className="space-y-3">
                <li className="flex items-start space-x-3">
                  <CheckCircle className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-sm">
                    Get professional proposals instantly
                  </span>
                </li>
                <li className="flex items-start space-x-3">
                  <CheckCircle className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-sm">
                    No waiting for email responses
                  </span>
                </li>
                <li className="flex items-start space-x-3">
                  <CheckCircle className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-sm">
                    Customizable for any project type
                  </span>
                </li>
                <li className="flex items-start space-x-3">
                  <CheckCircle className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                  <span className="text-sm">100% free with no limitations</span>
                </li>
              </ul>
            </div>

            {/* CTA */}
            <div className="p-6 rounded-2xl bg-gradient-to-br from-gray-900 to-black text-white">
              <h4 className="text-xl font-bold mb-4">
                Ready to Work Together?
              </h4>
              <p className="text-gray-300 mb-6">
                Generate your proposal now and let's start building amazing
                things together!
              </p>
              <button
                onClick={generatePDF}
                className="w-full py-3 px-6 bg-white text-gray-900 font-bold rounded-lg hover:bg-gray-100 transition-colors flex items-center justify-center"
              >
                <FileText className="h-5 w-5 mr-2" />
                Generate My Free Proposal
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AutomatedProposal;
